language: r
cache: packages
notifications:
    email:
        hannahiweller@gmail.com
addons:
 apt:
   update: true
   sources:
     - sourceline: 'ppa:opencpu/imagemagick'
   packages:
     - libmagick++-dev
