language: r
cache: packages
notifications:
    email:
        hannahiweller@gmail.com
env:
 global:
   - _R_CHECK_FORCE_SUGGESTS_: false
before_install:
  - R -e 'install.packages("rgdal", repos="http://R-Forge.R-project.org")'
addons:
 apt:
   update: true
   sources:
     - sourceline: 'ppa:opencpu/imagemagick'
   packages:
     - libmagick++-dev
     - libglu1-mesa-dev
     - libudunits2-dev
     - gdal-bin
